### ISSUE TITLE
Not SHA-3

### ISSUE THREAD

**Issue by mpaland** [emn178/js-sha3#1]
Please be aware that your algorithm is the old suggestion of NIST.
The update in 4/2014 adds padding (01), so what you are testing and implementing is basically Keccak - but not SHA-3 anymore!
See the new NIST test vectors, please.

**Comment by emn178** [comment]
ok, it's better to rename the method first.

2015-03-18 1:33 GMT+08:00 Marco Paland <notifications@github.com>:

**Comment by emn178** [comment]
I renamed to keccak and added 2014 sha3 implementation. 
thanks.
