### ISSUE TITLE
Feature request: KMAC and cShake

### ISSUE THREAD

**Issue by paulg446** [emn178/js-sha3#11]
Any plans of implementing KMAC and cShake? http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-185.pdf

Given that you've already implemented Shake and SHA3, and SHA3 doesn't suffer from length-extension attacks (so HMAC is not necessary), and KMAC is the new standard, it seems like a logical progression. Anyway, great library!

**Comment by emn178** [comment]
I will study and try when I have time..

**Comment by emn178** [comment]
Hi, I have pushed this two methods to master. Please try it. If it's ok, I will publish the package later.

**Comment by emn178** [comment]
published
