### ISSUE TITLE
Examples are great, please add a little tip for node users

### ISSUE THREAD

**Issue by truedat101** [emn178/js-sha3#17]
To get going on node.js, something like:

var jssha3 = require('js-sha3');

works after installing js-sha3 via NPM.  Thank you for this implementation.  This is an impressive piece of work.

**Comment by rsodre** [comment]
This works for me...

`
import { keccak_256 } from 'js-sha3';
// or...
var keccak_256 = require('js-sha3').keccak_256;

var result = keccak_256.update('Hello World!').hex();
`

**Comment by emn178** [comment]
I added title in README 
https://github.com/emn178/js-sha3#nodejs
