### ISSUE TITLE
Feature Request: KangarooTwelve and MarsupilamiFourteen

### ISSUE THREAD

**Issue by DonaldTsang** [emn178/js-sha3#18]
Reference: https://github.com/XKCP/XKCP/blob/master/Standalone/KangarooTwelve/Python/K12.py  
https://keccak.team/kangarootwelve.html and https://keccak.team/files/KangarooTwelve.pdf

**Comment by DonaldTsang** [comment]
This looks good, but pure JS vs pure TS seems to differ in ease-of-usage

**Comment by paulmillr** [comment]
- @DonaldTsang not really. Typescript is compiled to JS. We distribute js libs and js npm package. Typescript is extremely useful for typings / developer experience and I would argue it's easier with them than without them.

**Comment by DonaldTsang** [comment]
For those that are beginner, it would be useful to have a compiled JS script to be in the repo as well.
