### ISSUE TITLE
unhandled promise rejection

### ISSUE THREAD

**Issue by BernardA** [emn178/js-sha3#22]
I have a Gatsby app that is throwing the error below when building it for development ( did not test for production )

So in terminal I run: `gatsby develop`

Then the error below is thrown after queries are executed. It will output 3 times what appears to be the same error: 

>  success onPostBootstrap - 0.123s
> ⠀
> info bootstrap finished - 155.297 s
> ⠀
> success run queries - 206.420s - 1018/1018 4.93/s
> [=======                     ]   206.423 s 1/4 25% Generating image thumbnails
> (node:2655) UnhandledPromiseRejectionWarning: Error: input is invalid type
>     at Keccak../node_modules/js-sha3/src/sha3.js.Keccak.update (/Users/bernardo/Sites/quiamo/public/render-page.js:243196:15)
>     at /Users/bernardo/Sites/quiamo/public/render-page.js:243055:46
>     at getPaths (/Users/bernardo/Sites/quiamo/public/render-page.js:201337:29)
>     at Object.create (/Users/bernardo/Sites/quiamo/public/render-page.js:201645:19)
>     at _prepareChannel (/Users/bernardo/Sites/quiamo/public/render-page.js:199839:37)
>     at new BroadcastChannel (/Users/bernardo/Sites/quiamo/public/render-page.js:199719:3)
>     at createStateSyncMiddleware (/Users/bernardo/Sites/quiamo/public/render-page.js:311129:19)
>     at Module../src/store/reduxWrapper.js (/Users/bernardo/Sites/quiamo/public/render-page.js:319235:104)
>     at __webpack_require__ (/Users/bernardo/Sites/quiamo/public/render-page.js:30:30)
>     at Module../gatsby-ssr.js (/Users/bernardo/Sites/quiamo/public/render-page.js:1692:81)
>     at __webpack_require__ (/Users/bernardo/Sites/quiamo/public/render-page.js:30:30)
>     at Object../.cache/api-runner-ssr.js (/Users/bernardo/Sites/quiamo/public/render-page.js:134:11)
>     at __webpack_require__ (/Users/bernardo/Sites/quiamo/public/render-page.js:30:30)
>     at Module../.cache/develop-static-entry.js (/Users/bernardo/Sites/quiamo/public/render-page.js:467:73)
>     at __webpack_require__ (/Users/bernardo/Sites/quiamo/public/render-page.js:30:30)
>     at /Users/bernardo/Sites/quiamo/public/render-page.js:94:18
> (node:2655) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
> (node:2655) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Environment: 
node v12.16.0

**Comment by emn178** [comment]
Error: input is invalid type
at Keccak../node_modules/js-sha3/src/sha3.js.Keccak.update

please check your input?

**Comment by BernardA** [comment]
Thanks @emn178 but I left Gatsby long ago. I am closing this.
