### ISSUE TITLE
Suggestion: ArrayBuffer() as output

### ISSUE THREAD

**Issue by adon-at-work** [emn178/js-sha3#4]
I'd like to use it with `ArrayBuffer()` instead of a hex string as output. I can then further manipulate the bytes. I have made a local copy to get this done, and would like to see if you want me to contribute a PR for that.

**Comment by emn178** [comment]
Thanks for suggestion, I will try to add the features in the future.

**Comment by emn178** [comment]
Hi,

Now you can use something like sha3_512.buffer(...) to get ArrayBuffer output.
Please try it.

**Comment by adon-at-work** [comment]
I see your new implementation. Thanks :+1:
