### ISSUE TITLE
The files downloaded from npm are different from the files downloaded from github

### ISSUE THREAD

**Issue by nolsherry** [emn178/js-sha3#7]
Hello @emn178,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
I have downloaded the version 0.5.2 in [npm](https://www.npmjs.com/package/js-sha3), but I found that the files are not the same as the files which downloaded from [github](https://github.com/emn178/js-sha3/tree/v0.5.2), 
Could you help me update the files in npm? Thank you very much!

cdnjs/cdnjs#5766

**Comment by emn178** [comment]
hi, added files to v0.5.3.

**Comment by nolsherry** [comment]
@emn178, thanks for your help.  :+1:
